name: Release Build
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
      
    - name: Generate app icons
      run: flutter pub run flutter_launcher_icons
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
      
    - name: Build iOS
      run: |
        cd ios
        rm -rf Pods
        rm -rf Podfile.lock
        pod repo update
        pod install --repo-update
        cd ..
        flutter build ios --release --no-codesign
        cd build/ios/iphoneos
        mkdir Payload
        cp -r Runner.app Payload
        zip -r app.ipa Payload
        
    - name: Setup GitHub CLI
      run: |
        brew install gh
        echo "${{ secrets.TOKEN }}" | gh auth login --with-token
        
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        gh release create ${{ github.ref_name }} \
          --title "Release ${{ github.ref_name }}" \
          --notes "Release ${{ github.ref_name }}" \
          build/ios/iphoneos/app.ipa